---
abstract: 'Curate a repository of Perl modules'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  File::Which: 0
  Log::Dispatch::Handle: 0
  Module::Build: 0.3601
  Test::File: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto:
    file: lib/Pinto.pm
    version: 0.040_002
  Pinto::Action:
    file: lib/Pinto/Action.pm
    version: 0.040_002
  Pinto::Action::Add:
    file: lib/Pinto/Action/Add.pm
    version: 0.040_002
  Pinto::Action::Copy:
    file: lib/Pinto/Action/Copy.pm
    version: 0.040_002
  Pinto::Action::Edit:
    file: lib/Pinto/Action/Edit.pm
    version: 0.040_002
  Pinto::Action::Install:
    file: lib/Pinto/Action/Install.pm
    version: 0.040_002
  Pinto::Action::List:
    file: lib/Pinto/Action/List.pm
    version: 0.040_002
  Pinto::Action::Merge:
    file: lib/Pinto/Action/Merge.pm
    version: 0.040_002
  Pinto::Action::New:
    file: lib/Pinto/Action/New.pm
    version: 0.040_002
  Pinto::Action::Nop:
    file: lib/Pinto/Action/Nop.pm
    version: 0.040_002
  Pinto::Action::Pin:
    file: lib/Pinto/Action/Pin.pm
    version: 0.040_002
  Pinto::Action::Props:
    file: lib/Pinto/Action/Props.pm
    version: 0.040_002
  Pinto::Action::Pull:
    file: lib/Pinto/Action/Pull.pm
    version: 0.040_002
  Pinto::Action::Stacks:
    file: lib/Pinto/Action/Stacks.pm
    version: 0.040_002
  Pinto::Action::Statistics:
    file: lib/Pinto/Action/Statistics.pm
    version: 0.040_002
  Pinto::Action::Unpin:
    file: lib/Pinto/Action/Unpin.pm
    version: 0.040_002
  Pinto::Action::Verify:
    file: lib/Pinto/Action/Verify.pm
    version: 0.040_002
  Pinto::Config:
    file: lib/Pinto/Config.pm
    version: 0.040_002
  Pinto::Database:
    file: lib/Pinto/Database.pm
    version: 0.040_002
  Pinto::IndexCache:
    file: lib/Pinto/IndexCache.pm
    version: 0.040_002
  Pinto::IndexWriter:
    file: lib/Pinto/IndexWriter.pm
    version: 0.040_002
  Pinto::Initializer:
    file: lib/Pinto/Initializer.pm
    version: 0.040_002
  Pinto::Locker:
    file: lib/Pinto/Locker.pm
    version: 0.040_002
  Pinto::Logger:
    file: lib/Pinto/Logger.pm
    version: 0.040_002
  Pinto::PackageExtractor:
    file: lib/Pinto/PackageExtractor.pm
    version: 0.040_002
  Pinto::Repository:
    file: lib/Pinto/Repository.pm
    version: 0.040_002
  Pinto::Result:
    file: lib/Pinto/Result.pm
    version: 0.040_002
  Pinto::Role::Configurable:
    file: lib/Pinto/Role/Configurable.pm
    version: 0.040_002
  Pinto::Role::FileFetcher:
    file: lib/Pinto/Role/FileFetcher.pm
    version: 0.040_002
  Pinto::Role::Loggable:
    file: lib/Pinto/Role/Loggable.pm
    version: 0.040_002
  Pinto::Role::PackageImporter:
    file: lib/Pinto/Role/PackageImporter.pm
    version: 0.040_002
  Pinto::Role::PathMaker:
    file: lib/Pinto/Role/PathMaker.pm
    version: 0.040_002
  Pinto::Role::Schema::Result:
    file: lib/Pinto/Role/Schema/Result.pm
    version: 0.040_002
  Pinto::Schema:
    file: lib/Pinto/Schema.pm
    version: 0.040_002
  Pinto::Schema::Result::Distribution:
    file: lib/Pinto/Schema/Result/Distribution.pm
    version: 0.040_002
  Pinto::Schema::Result::Package:
    file: lib/Pinto/Schema/Result/Package.pm
    version: 0.040_002
  Pinto::Schema::Result::Prerequisite:
    file: lib/Pinto/Schema/Result/Prerequisite.pm
    version: 0.040_002
  Pinto::Schema::Result::Registration:
    file: lib/Pinto/Schema/Result/Registration.pm
    version: 0.040_002
  Pinto::Schema::Result::Stack:
    file: lib/Pinto/Schema/Result/Stack.pm
    version: 0.040_002
  Pinto::Schema::Result::StackProperty:
    file: lib/Pinto/Schema/Result/StackProperty.pm
    version: 0.040_002
  Pinto::Statistics:
    file: lib/Pinto/Statistics.pm
    version: 0.040_002
  Pinto::Store:
    file: lib/Pinto/Store.pm
    version: 0.040_002
  Pinto::Store::File:
    file: lib/Pinto/Store/File.pm
    version: 0.040_002
  Pinto::Tester:
    file: lib/Pinto/Tester.pm
    version: 0.040_002
  Pinto::Tester::Util:
    file: lib/Pinto/Tester/Util.pm
    version: 0.040_002
  Pinto::Util:
    file: lib/Pinto/Util.pm
    version: 0.040_002
requires:
  CPAN::Checksums: 0
  CPAN::DistnameInfo: 0
  Carp: 0
  Class::Load: 0
  DBD::SQLite: 1.33
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  Digest::MD5: 0
  Digest::SHA: 0
  Dist::Metadata: 0.922
  Dist::Requires: 0.005
  Exporter: 0
  File::Temp: 0
  IO::String: 0
  LWP::UserAgent: 0
  LockFile::Simple: 0
  Log::Dispatch: 0
  Log::Dispatch::File: 0
  Module::Faker::Dist: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Aliases: 0
  MooseX::Configuration: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  MooseX::Types::Log::Dispatch: 0
  MooseX::Types::Moose: 0
  Package::Locator: 0.006
  Path::Class: 0
  PerlIO::gzip: 0
  Pinto::Common: 0.040_002
  Pinto::DistributionSpec: 0
  Pinto::Exception: 0
  Pinto::PackageSpec: 0
  Pinto::Role::Interface::Action::Add: 0
  Pinto::Role::Interface::Action::Copy: 0
  Pinto::Role::Interface::Action::Edit: 0
  Pinto::Role::Interface::Action::Install: 0
  Pinto::Role::Interface::Action::List: 0
  Pinto::Role::Interface::Action::Merge: 0
  Pinto::Role::Interface::Action::New: 0
  Pinto::Role::Interface::Action::Nop: 0
  Pinto::Role::Interface::Action::Pin: 0
  Pinto::Role::Interface::Action::Props: 0
  Pinto::Role::Interface::Action::Pull: 0
  Pinto::Role::Interface::Action::Stacks: 0
  Pinto::Role::Interface::Action::Statistics: 0
  Pinto::Role::Interface::Action::Unpin: 0
  Pinto::Role::Interface::Action::Verify: 0
  Pinto::Types: 0
  Readonly: 0
  SQL::Translator: 0.11009
  Scalar::Util: 0
  String::Format: 0
  Test::Builder::Module: 0
  Test::Exception: 0
  Test::Log::Dispatch: 0
  Try::Tiny: 0
  URI: 0
  autodie: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.008
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto/issues
  repository: git://github.com/thaljef/Pinto.git
version: 0.040_002
