---
abstract: 'Curate a repository of Perl modules'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Find: 0
  Log::Dispatch::Handle: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  App::Pinto::Admin:
    file: lib/App/Pinto/Admin.pm
    version: 0.040_001
  App::Pinto::Admin::Command:
    file: lib/App/Pinto/Admin/Command.pm
    version: 0.040_001
  App::Pinto::Admin::Command::add:
    file: lib/App/Pinto/Admin/Command/add.pm
    version: 0.040_001
  App::Pinto::Admin::Command::create:
    file: lib/App/Pinto/Admin/Command/create.pm
    version: 0.040_001
  App::Pinto::Admin::Command::list:
    file: lib/App/Pinto/Admin/Command/list.pm
    version: 0.040_001
  App::Pinto::Admin::Command::manual:
    file: lib/App/Pinto/Admin/Command/manual.pm
    version: 0.040_001
  App::Pinto::Admin::Command::nop:
    file: lib/App/Pinto/Admin/Command/nop.pm
    version: 0.040_001
  App::Pinto::Admin::Command::pin:
    file: lib/App/Pinto/Admin/Command/pin.pm
    version: 0.040_001
  App::Pinto::Admin::Command::pull:
    file: lib/App/Pinto/Admin/Command/pull.pm
    version: 0.040_001
  App::Pinto::Admin::Command::stack:
    file: lib/App/Pinto/Admin/Command/stack.pm
    version: 0.040_001
  App::Pinto::Admin::Command::statistics:
    file: lib/App/Pinto/Admin/Command/statistics.pm
    version: 0.040_001
  App::Pinto::Admin::Command::unpin:
    file: lib/App/Pinto/Admin/Command/unpin.pm
    version: 0.040_001
  App::Pinto::Admin::Command::verify:
    file: lib/App/Pinto/Admin/Command/verify.pm
    version: 0.040_001
  App::Pinto::Admin::Command::version:
    file: lib/App/Pinto/Admin/Command/version.pm
    version: 0.040_001
  App::Pinto::Admin::DispatchingCommand:
    file: lib/App/Pinto/Admin/DispatchingCommand.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand:
    file: lib/App/Pinto/Admin/Subcommand.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::copy:
    file: lib/App/Pinto/Admin/Subcommand/stack/copy.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::create:
    file: lib/App/Pinto/Admin/Subcommand/stack/create.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::edit:
    file: lib/App/Pinto/Admin/Subcommand/stack/edit.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::list:
    file: lib/App/Pinto/Admin/Subcommand/stack/list.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::merge:
    file: lib/App/Pinto/Admin/Subcommand/stack/merge.pm
    version: 0.040_001
  App::Pinto::Admin::Subcommand::stack::props:
    file: lib/App/Pinto/Admin/Subcommand/stack/props.pm
    version: 0.040_001
  Pinto:
    file: lib/Pinto.pm
    version: 0.040_001
  Pinto::Action:
    file: lib/Pinto/Action.pm
    version: 0.040_001
  Pinto::Action::Add:
    file: lib/Pinto/Action/Add.pm
    version: 0.040_001
  Pinto::Action::List:
    file: lib/Pinto/Action/List.pm
    version: 0.040_001
  Pinto::Action::Nop:
    file: lib/Pinto/Action/Nop.pm
    version: 0.040_001
  Pinto::Action::Pin:
    file: lib/Pinto/Action/Pin.pm
    version: 0.040_001
  Pinto::Action::Pull:
    file: lib/Pinto/Action/Pull.pm
    version: 0.040_001
  Pinto::Action::Stack::Copy:
    file: lib/Pinto/Action/Stack/Copy.pm
    version: 0.040_001
  Pinto::Action::Stack::Create:
    file: lib/Pinto/Action/Stack/Create.pm
    version: 0.040_001
  Pinto::Action::Stack::Edit:
    file: lib/Pinto/Action/Stack/Edit.pm
    version: 0.040_001
  Pinto::Action::Stack::List:
    file: lib/Pinto/Action/Stack/List.pm
    version: 0.040_001
  Pinto::Action::Stack::Merge:
    file: lib/Pinto/Action/Stack/Merge.pm
    version: 0.040_001
  Pinto::Action::Stack::Props:
    file: lib/Pinto/Action/Stack/Props.pm
    version: 0.040_001
  Pinto::Action::Statistics:
    file: lib/Pinto/Action/Statistics.pm
    version: 0.040_001
  Pinto::Action::Unpin:
    file: lib/Pinto/Action/Unpin.pm
    version: 0.040_001
  Pinto::Action::Verify:
    file: lib/Pinto/Action/Verify.pm
    version: 0.040_001
  Pinto::Config:
    file: lib/Pinto/Config.pm
    version: 0.040_001
  Pinto::Creator:
    file: lib/Pinto/Creator.pm
    version: 0.040_001
  Pinto::Database:
    file: lib/Pinto/Database.pm
    version: 0.040_001
  Pinto::Exception:
    file: lib/Pinto/Exception.pm
    version: 0.040_001
  Pinto::IndexCache:
    file: lib/Pinto/IndexCache.pm
    version: 0.040_001
  Pinto::IndexWriter:
    file: lib/Pinto/IndexWriter.pm
    version: 0.040_001
  Pinto::Locker:
    file: lib/Pinto/Locker.pm
    version: 0.040_001
  Pinto::Logger:
    file: lib/Pinto/Logger.pm
    version: 0.040_001
  Pinto::PackageExtractor:
    file: lib/Pinto/PackageExtractor.pm
    version: 0.040_001
  Pinto::Repository:
    file: lib/Pinto/Repository.pm
    version: 0.040_001
  Pinto::Result:
    file: lib/Pinto/Result.pm
    version: 0.040_001
  Pinto::Role::Configurable:
    file: lib/Pinto/Role/Configurable.pm
    version: 0.040_001
  Pinto::Role::FileFetcher:
    file: lib/Pinto/Role/FileFetcher.pm
    version: 0.040_001
  Pinto::Role::Loggable:
    file: lib/Pinto/Role/Loggable.pm
    version: 0.040_001
  Pinto::Role::PackageImporter:
    file: lib/Pinto/Role/PackageImporter.pm
    version: 0.040_001
  Pinto::Role::PathMaker:
    file: lib/Pinto/Role/PathMaker.pm
    version: 0.040_001
  Pinto::Role::Schema::Result:
    file: lib/Pinto/Role/Schema/Result.pm
    version: 0.040_001
  Pinto::Schema:
    file: lib/Pinto/Schema.pm
    version: 0.040_001
  Pinto::Schema::Result::Distribution:
    file: lib/Pinto/Schema/Result/Distribution.pm
    version: 0.040_001
  Pinto::Schema::Result::Package:
    file: lib/Pinto/Schema/Result/Package.pm
    version: 0.040_001
  Pinto::Schema::Result::Prerequisite:
    file: lib/Pinto/Schema/Result/Prerequisite.pm
    version: 0.040_001
  Pinto::Schema::Result::Registration:
    file: lib/Pinto/Schema/Result/Registration.pm
    version: 0.040_001
  Pinto::Schema::Result::Stack:
    file: lib/Pinto/Schema/Result/Stack.pm
    version: 0.040_001
  Pinto::Schema::Result::StackProperty:
    file: lib/Pinto/Schema/Result/StackProperty.pm
    version: 0.040_001
  Pinto::Statistics:
    file: lib/Pinto/Statistics.pm
    version: 0.040_001
  Pinto::Store:
    file: lib/Pinto/Store.pm
    version: 0.040_001
  Pinto::Store::File:
    file: lib/Pinto/Store/File.pm
    version: 0.040_001
  Pinto::Tester:
    file: lib/Pinto/Tester.pm
    version: 0.040_001
  Pinto::Tester::Util:
    file: lib/Pinto/Tester/Util.pm
    version: 0.040_001
  Pinto::Util:
    file: lib/Pinto/Util.pm
    version: 0.040_001
requires:
  App::Cmd::Setup: 0
  App::Cmd::Subdispatch: 0
  CPAN::Checksums: 0
  CPAN::DistnameInfo: 0
  Carp: 0
  Class::Load: 0
  DBD::SQLite: 1.33
  DBIx::Class::Core: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  Digest::MD5: 0
  Digest::SHA: 0
  Dist::Metadata: 0.922
  Dist::Requires: 0.005
  Exporter: 0
  File::Temp: 0
  IO::String: 0
  LWP::UserAgent: 0
  List::Util: 0
  LockFile::Simple: 0
  Log::Dispatch: 0
  Log::Dispatch::File: 0
  Log::Dispatch::Screen: 0
  Log::Dispatch::Screen::Color: 0
  Module::Faker::Dist: 0
  Moose: 0
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::Aliases: 0
  MooseX::Configuration: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  MooseX::Types::Log::Dispatch: 0
  MooseX::Types::Moose: 0
  Package::Locator: 0.004
  Path::Class: 0
  PerlIO::gzip: 0
  Pinto::Common: 0.040_001
  Pinto::Constants: 0
  Pinto::DistributionSpec: 0
  Pinto::PackageSpec: 0
  Pinto::Role::Interface::Action::Add: 0
  Pinto::Role::Interface::Action::List: 0
  Pinto::Role::Interface::Action::Nop: 0
  Pinto::Role::Interface::Action::Pin: 0
  Pinto::Role::Interface::Action::Pull: 0
  Pinto::Role::Interface::Action::Stack::Copy: 0
  Pinto::Role::Interface::Action::Stack::Create: 0
  Pinto::Role::Interface::Action::Stack::Edit: 0
  Pinto::Role::Interface::Action::Stack::List: 0
  Pinto::Role::Interface::Action::Stack::Props: 0
  Pinto::Role::Interface::Action::Statistics: 0
  Pinto::Role::Interface::Action::Unpin: 0
  Pinto::Role::Interface::Action::Verify: 0
  Pinto::Types: 0
  Pod::Usage: 0
  Readonly: 0
  SQL::Translator: 0.11009
  Scalar::Util: 0
  String::Format: 0
  Test::Builder::Module: 0
  Test::Exception: 0
  Test::Log::Dispatch: 0
  Throwable::Error: 0
  Try::Tiny: 0
  URI: 0
  autodie: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  perl: 5.008
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto/issues
  repository: git://github.com/thaljef/Pinto.git
version: 0.040_001
