---
abstract: 'Perl archive repository manager'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@imaginative-software.com>'
build_requires:
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  App::Pinto:
    file: lib/App/Pinto.pm
    version: 0.002
  App::Pinto::Command:
    file: lib/App/Pinto/Command.pm
    version: 0.002
  App::Pinto::Command::add:
    file: lib/App/Pinto/Command/add.pm
    version: 0.002
  App::Pinto::Command::clean:
    file: lib/App/Pinto/Command/clean.pm
    version: 0.002
  App::Pinto::Command::create:
    file: lib/App/Pinto/Command/create.pm
    version: 0.002
  App::Pinto::Command::list:
    file: lib/App/Pinto/Command/list.pm
    version: 0.002
  App::Pinto::Command::remove:
    file: lib/App/Pinto/Command/remove.pm
    version: 0.002
  App::Pinto::Command::update:
    file: lib/App/Pinto/Command/update.pm
    version: 0.002
  App::Pinto::Command::verify:
    file: lib/App/Pinto/Command/verify.pm
    version: 0.002
  Pinto:
    file: lib/Pinto.pm
    version: 0.002
  Pinto::Config:
    file: lib/Pinto/Config.pm
    version: 0.002
  Pinto::Index:
    file: lib/Pinto/Index.pm
    version: 0.002
  Pinto::Package:
    file: lib/Pinto/Package.pm
    version: 0.002
  Pinto::Role::Log:
    file: lib/Pinto/Role/Log.pm
    version: 0.002
  Pinto::Store:
    file: lib/Pinto/Store.pm
    version: 0.002
  Pinto::Store::Svn:
    file: lib/Pinto/Store/Svn.pm
    version: 0.002
  Pinto::UserAgent:
    file: lib/Pinto/UserAgent.pm
    version: 0.002
  Pinto::Util:
    file: lib/Pinto/Util.pm
    version: 0.002
  Pinto::Util::Svn:
    file: lib/Pinto/Util/Svn.pm
    version: 0.002
requires:
  App::Cmd::Setup: 0
  Carp: 0
  Class::Load: 0
  Compress::Zlib: 0
  Config::Tiny: 0
  Date::Format: 0
  Dist::Metadata: 0
  Exporter: 0
  File::Copy: 0
  File::Find: 0
  File::HomeDir: 0
  IPC::Cmd: 0.72
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Role: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Path::Class::File: 0
  Readonly: 0
  URI: 0
  overload: 0
  perl: 5.008
resources:
  homepage: https://github.com/thaljef/Pinto
  repository: https://github.com/thaljef/Pinto
version: 0.002
