---
abstract: 'Curate a repository of Perl modules'
author:
  - 'Jeffrey Ryan Thalhammer <jeff@stratopan.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  Module::Build: 0.3601
  Test::File: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300032, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pinto
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
provides:
  Pinto:
    file: lib/Pinto.pm
    version: 0.067
  Pinto::Action:
    file: lib/Pinto/Action.pm
    version: 0.067
  Pinto::Action::Add:
    file: lib/Pinto/Action/Add.pm
    version: 0.067
  Pinto::Action::Clean:
    file: lib/Pinto/Action/Clean.pm
    version: 0.067
  Pinto::Action::Copy:
    file: lib/Pinto/Action/Copy.pm
    version: 0.067
  Pinto::Action::Default:
    file: lib/Pinto/Action/Default.pm
    version: 0.067
  Pinto::Action::Delete:
    file: lib/Pinto/Action/Delete.pm
    version: 0.067
  Pinto::Action::Diff:
    file: lib/Pinto/Action/Diff.pm
    version: 0.067
  Pinto::Action::Install:
    file: lib/Pinto/Action/Install.pm
    version: 0.067
  Pinto::Action::Kill:
    file: lib/Pinto/Action/Kill.pm
    version: 0.067
  Pinto::Action::List:
    file: lib/Pinto/Action/List.pm
    version: 0.067
  Pinto::Action::Lock:
    file: lib/Pinto/Action/Lock.pm
    version: 0.067
  Pinto::Action::Log:
    file: lib/Pinto/Action/Log.pm
    version: 0.067
  Pinto::Action::New:
    file: lib/Pinto/Action/New.pm
    version: 0.067
  Pinto::Action::Nop:
    file: lib/Pinto/Action/Nop.pm
    version: 0.067
  Pinto::Action::Pin:
    file: lib/Pinto/Action/Pin.pm
    version: 0.067
  Pinto::Action::Props:
    file: lib/Pinto/Action/Props.pm
    version: 0.067
  Pinto::Action::Pull:
    file: lib/Pinto/Action/Pull.pm
    version: 0.067
  Pinto::Action::Register:
    file: lib/Pinto/Action/Register.pm
    version: 0.067
  Pinto::Action::Rename:
    file: lib/Pinto/Action/Rename.pm
    version: 0.067
  Pinto::Action::Stacks:
    file: lib/Pinto/Action/Stacks.pm
    version: 0.067
  Pinto::Action::Statistics:
    file: lib/Pinto/Action/Statistics.pm
    version: 0.067
  Pinto::Action::Unlock:
    file: lib/Pinto/Action/Unlock.pm
    version: 0.067
  Pinto::Action::Unpin:
    file: lib/Pinto/Action/Unpin.pm
    version: 0.067
  Pinto::Action::Unregister:
    file: lib/Pinto/Action/Unregister.pm
    version: 0.067
  Pinto::Action::Verify:
    file: lib/Pinto/Action/Verify.pm
    version: 0.067
  Pinto::ArchiveUnpacker:
    file: lib/Pinto/ArchiveUnpacker.pm
    version: 0.067
  Pinto::Chrome:
    file: lib/Pinto/Chrome.pm
    version: 0.067
  Pinto::Chrome::Term:
    file: lib/Pinto/Chrome/Term.pm
    version: 0.067
  Pinto::CommitMessage:
    file: lib/Pinto/CommitMessage.pm
    version: 0.067
  Pinto::Config:
    file: lib/Pinto/Config.pm
    version: 0.067
  Pinto::Database:
    file: lib/Pinto/Database.pm
    version: 0.067
  Pinto::Difference:
    file: lib/Pinto/Difference.pm
    version: 0.067
  Pinto::DifferenceEntry:
    file: lib/Pinto/Difference.pm
    version: 0.067
  Pinto::IndexCache:
    file: lib/Pinto/IndexCache.pm
    version: 0.067
  Pinto::IndexWriter:
    file: lib/Pinto/IndexWriter.pm
    version: 0.067
  Pinto::Initializer:
    file: lib/Pinto/Initializer.pm
    version: 0.067
  Pinto::Locker:
    file: lib/Pinto/Locker.pm
    version: 0.067
  Pinto::Migrator:
    file: lib/Pinto/Migrator.pm
    version: 0.067
  Pinto::ModlistWriter:
    file: lib/Pinto/ModlistWriter.pm
    version: 0.067
  Pinto::PackageExtractor:
    file: lib/Pinto/PackageExtractor.pm
    version: 0.067
  Pinto::PrerequisiteWalker:
    file: lib/Pinto/PrerequisiteWalker.pm
    version: 0.067
  Pinto::Repository:
    file: lib/Pinto/Repository.pm
    version: 0.067
  Pinto::Result:
    file: lib/Pinto/Result.pm
    version: 0.067
  Pinto::RevisionWalker:
    file: lib/Pinto/RevisionWalker.pm
    version: 0.067
  Pinto::Role::Committable:
    file: lib/Pinto/Role/Committable.pm
    version: 0.067
  Pinto::Role::FileFetcher:
    file: lib/Pinto/Role/FileFetcher.pm
    version: 0.067
  Pinto::Role::Installer:
    file: lib/Pinto/Role/Installer.pm
    version: 0.067
  Pinto::Role::Plated:
    file: lib/Pinto/Role/Plated.pm
    version: 0.067
  Pinto::Role::Puller:
    file: lib/Pinto/Role/Puller.pm
    version: 0.067
  Pinto::Role::Schema::Result:
    file: lib/Pinto/Role/Schema/Result.pm
    version: 0.067
  Pinto::Role::Transactional:
    file: lib/Pinto/Role/Transactional.pm
    version: 0.067
  Pinto::Schema:
    file: lib/Pinto/Schema.pm
    version: 0.067
  Pinto::Schema::Result::Ancestry:
    file: lib/Pinto/Schema/Result/Ancestry.pm
    version: 0.067
  Pinto::Schema::Result::Distribution:
    file: lib/Pinto/Schema/Result/Distribution.pm
    version: 0.067
  Pinto::Schema::Result::Package:
    file: lib/Pinto/Schema/Result/Package.pm
    version: 0.067
  Pinto::Schema::Result::Prerequisite:
    file: lib/Pinto/Schema/Result/Prerequisite.pm
    version: 0.067
  Pinto::Schema::Result::Registration:
    file: lib/Pinto/Schema/Result/Registration.pm
    version: 0.067
  Pinto::Schema::Result::Revision:
    file: lib/Pinto/Schema/Result/Revision.pm
    version: 0.067
  Pinto::Schema::Result::Stack:
    file: lib/Pinto/Schema/Result/Stack.pm
    version: 0.067
  Pinto::Schema::ResultSet::Distribution:
    file: lib/Pinto/Schema/ResultSet/Distribution.pm
    version: 0.067
  Pinto::Schema::ResultSet::Package:
    file: lib/Pinto/Schema/ResultSet/Package.pm
    version: 0.067
  Pinto::Schema::ResultSet::Registration:
    file: lib/Pinto/Schema/ResultSet/Registration.pm
    version: 0.067
  Pinto::Statistics:
    file: lib/Pinto/Statistics.pm
    version: 0.067
  Pinto::Store:
    file: lib/Pinto/Store.pm
    version: 0.067
  Pinto::Tester:
    file: lib/Pinto/Tester.pm
    version: 0.067
  Pinto::Tester::Util:
    file: lib/Pinto/Tester/Util.pm
    version: 0.067
requires:
  Archive::Extract: 0
  Archive::Tar: 0
  CPAN::Checksums: 0
  CPAN::DistnameInfo: 0
  CPAN::Meta: 0
  Class::Load: 0
  Cwd: 0
  Cwd::Guard: 0
  DBD::SQLite: 1.33
  DBIx::Class: 0.08200
  DBIx::Class::Core: 0
  DBIx::Class::ResultSet: 0
  DBIx::Class::Schema: 0
  DateTime: 0
  DateTime::TimeZone: 0
  DateTime::TimeZone::OffsetOnly: 0
  Digest::SHA: 0
  Dist::Metadata: 0.924
  English: 0
  Exporter: 0
  File::Copy: 0
  File::Find: 0
  File::NFSLock: 0
  File::ShareDir: 0
  File::Temp: 0
  File::Which: 0
  HTTP::Date: 0
  HTTP::Tiny: 0
  IO::Handle: 0
  IO::Zlib: 0
  JSON: 0
  JSON::PP: 2.27103
  List::Util: 0
  Module::Faker::Dist: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Aliases: 0
  MooseX::Configuration: 0
  MooseX::MarkAsMethods: 0
  MooseX::NonMoose: 0
  MooseX::SetOnce: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Moose: 0
  Package::Locator: 0.006
  Path::Class: 0
  Pinto::Constants: 0.066
  Pinto::DistributionSpec: 0
  Pinto::Exception: 0
  Pinto::Globals: 0
  Pinto::PackageSpec: 0.066
  Pinto::Role::PauseConfig: 0
  Pinto::SpecFactory: 0
  Pinto::Types: 0.066
  Pinto::Util: 0.066
  Readonly: 0
  String::Format: 0
  Term::ANSIColor: 2.02
  Term::EditorEdit: 0
  Test::Builder::Module: 0
  Test::Exception: 0
  Try::Tiny: 0
  URI: 0
  base: 0
  overload: 0
  perl: 5.008
  strict: 0
  utf8: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/thaljef/Pinto/issues
  homepage: https://metacpan.org/module/Pinto::Manual
  repository: git://github.com/thaljef/Pinto.git
version: 0.067
