#!perl

# This test is generated by Dist::Zilla::Plugin::Test::PodSpelling

use Test::More;

eval "use Pod::Wordlist::hanekomu";
plan skip_all => "Pod::Wordlist::hanekomu required for testing POD spelling"
  if $@;

eval "use Test::Spelling 0.12";
plan skip_all => "Test::Spelling 0.12 required for testing POD spelling"
  if $@;

set_spell_cmd('aspell list');
add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
VCS
PASSed
ActionBatch
subclasses
noinit
nocleanup
nocommit
norecurse
devel
Reindex
reindex
reindexing
reindexed
reindexer
reindexes
Jeffrey
Ryan
Thalhammer
Imaginative
Software
Systems
lib
Pinto
Role
FileFetcher
Store
File
App
Admin
Svn
Schema
Result
Package
PackageImporter
Git
Action
Unpin
Command
import
mirror
Statistics
Configurable
Purge
Locker
Repository
nop
rebuild
manual
Loggable
Remove
Exceptions
Tester
Util
Logger
Remote
create
IndexWriter
IndexCache
unpin
PackageExtractor
Nop
Rebuild
purge
PathMaker
Clean
Mirror
Distribution
remove
version
list
Batch
Pin
add
Creator
clean
statistics
Config
pin
Import
verify
List
Add
Verify
Database

